import { Separator } from "@/components/ui/separator";
import HHCLogo from "../assets/logo-removebg-preview.png";
import html2canvas from "html2canvas";
import { HandHeart, Mail } from "lucide-react";
import {
  Area,
  AreaChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { useEffect, useRef, useState } from "react";
interface DonationReceiptProps {
  transactionDetails: any; // Adjust type based on your data structure
  receiptRef: React.RefObject<HTMLDivElement>;
}
const DonationReceipt: React.FC<DonationReceiptProps> = ({
  transactionDetails,
  receiptRef,
}) => {
  return (
    <div className="flex flex-col items-center p-4 max-w-full h-full mx-auto">
      {/* Hidden Receipt Content for Printing */}
      <div ref={receiptRef} className=" bg-white w-full p-4">
        {/* Logo */}
        <div className="flex items-center gap-x-10">
          <img src={HHCLogo} alt="Hope Horizon Logo" className="w-36 h-36" />
          <h4 className="text-2xl font-bold confortaa-apply">
            Hope Horizon -{" "}
            <span className="text-sm font-semibold">Charity & Fundraising</span>
          </h4>
        </div>
        <div className="flex items-center justify-between pr-1">
          <h2 className="text-xl font-bold text-gray-800 my-2">
            Donation Receipt
          </h2>
          <h4 className="text-sm font-bold text-gray-500 my-2">
            No: hhc#[{transactionDetails._id}]
          </h4>
        </div>
        <Separator className="text-primary bg-primary" />
        <div className="flex items-center gap-x-10 my-3">
          {/* Event Cover Photo */}
          <img
            src={transactionDetails.event.coverPhotoHighQuality}
            alt="Event Cover"
            className="w-[100px] h-[100px] rounded-md "
          />
          <h4 className="text-2xl font-bold">
            {transactionDetails.event.Event_name}
          </h4>
        </div>

        {/* Donation Details */}
        <div className="my-4 text-gray-700 text-left">
          <p>
            <strong>Transaction ID:</strong> {transactionDetails._id}
          </p>
          <p>
            <strong>Donor Name:</strong> {transactionDetails.user.username}
          </p>
          <p>
            <strong>Donor Email:</strong> {transactionDetails.user.email}
          </p>
          <p>
            <strong>Event:</strong> {transactionDetails.event.Event_name}
          </p>
          <p>
            <strong>Amount:</strong> ₹{transactionDetails.amount}
          </p>
          <p>
            <strong>Date:</strong>{" "}
            {transactionDetails.donation_date.split("T")[0]}{" "}
            {transactionDetails.donation_date.split("T")[1]}
          </p>
          <p>
            <strong>Mihpayid:</strong> {transactionDetails.mihpayid}
          </p>
          <p>
            <strong>Mode:</strong> {transactionDetails.mode}
          </p>
          {transactionDetails.bank_ref_num && (
            <p>
              <strong>Bank Reference No.:</strong>{" "}
              {transactionDetails.bank_ref_num}
            </p>
          )}
          {transactionDetails.cardnum && (
            <p>
              <strong>Debit/Credit Card Number :</strong>{" "}
              {transactionDetails.cardnum}
            </p>
          )}
          {transactionDetails.upi_transaction_id && (
            <p>
              <strong>Upi Transaction ID:</strong>{" "}
              {transactionDetails.upi_transaction_id}
            </p>
          )}
          {transactionDetails.wallet && (
            <p>
              <strong>Wallet:</strong> {transactionDetails.wallet}
            </p>
          )}
          <div className="flex flex-col gap-y-2 items-center mt-16">
            <h4 className="text-center text-3xl font-bold confortaa-apply flex gap-x-2 items-center overflow-hidden">
              <HandHeart size={30} />
              <span className="text-transparent bg-clip-text bg-gradient-to-r from-primary via-primary/70 to-[#f3ab30] border-0">
                Thank you{" "}
              </span>
            </h4>
            <p>For your valuable contribution. This means a lot to us </p>
          </div>
        </div>

        {/* Footer */}
        <div className="fixed bottom-4 text-gray-500 text-xs w-full ">
          <Separator className="text-primary bg-primary w-full" />
          <p>*Report generated by system on {new Date().toLocaleString()}</p>
          <p>
            Hope Horizon - Charity & Fundraising .&copy; 2025 All Rights
            Reserved{" "}
          </p>
          <p>Registered under the Trust Act of India</p>
          <div className="flex items-center gap-x-2">
            <h5>Contact Us</h5>
            <h5 className="flex items-center gap-x-2">
              <Mail size={15} /> donate@hopehorizon.org
            </h5>
          </div>
        </div>
      </div>
    </div>
  );
};

export default DonationReceipt;

export function ReportContent({
  filteredData,
  timeframe,
  receiptRef,
  chartImage,
}: {
  filteredData: any;
  timeframe: any;
  receiptRef: React.RefObject<HTMLDivElement>;
  chartImage: string | null;
}) {
  const eventDonations = filteredData.reduce(
    (acc: Record<string, number>, donation: any) => {
      const eventName = donation.event?.Event_name || "Unknown Event";
      acc[eventName] = (acc[eventName] || 0) + donation.amount;
      return acc;
    },
    {}
  );

  const sortedEvents = Object.entries(eventDonations).sort(
    (a, b) => b[1] - a[1]
  );

  const topDonatedEvent =
    sortedEvents.length > 0 ? sortedEvents[0] : ["N/A", 0];
  const leastDonatedEvent =
    sortedEvents.length > 1
      ? sortedEvents[sortedEvents.length - 1]
      : ["N/A", 0];
  return (
    <div ref={receiptRef} className="p-6">
      <div className="flex items-center gap-x-10">
        <img src={HHCLogo} alt="Hope Horizon Logo" className="w-36 h-36" />
        <h4 className="text-2xl font-bold confortaa-apply">
          Hope Horizon -{" "}
          <span className="text-sm font-semibold">Charity & Fundraising</span>
        </h4>
      </div>
      <div className="flex items-center justify-between pr-1">
        <h2 className="text-xl font-bold text-gray-800 my-2">
          Donation Report for {timeframe} donation data.
        </h2>
      </div>
      <Separator className="text-primary bg-primary" />
      <p className="mb-2 text-lg">Report Timeframe: {timeframe}</p>
      <p className="mb-2">Total Donations: {filteredData.length}</p>
      <p className="mb-2">
        Total Amount: ₹
        {filteredData.reduce((sum: any, d: any) => sum + d.amount, 0)}
      </p>
      {topDonatedEvent && (
        <p className="mb-4">
          Top Donated Event: {topDonatedEvent[0].toString()}{" "}
        </p>
      )}
      {leastDonatedEvent && (
        <p className="mb-10">
          Least Donated Event: {leastDonatedEvent[0].toString()}{" "}
        </p>
      )}
      {chartImage && (
        <img src={chartImage} alt="Donation Graph" className="w-full h-80" />
      )}
      <div className="fixed bottom-4 text-gray-500 text-xs w-full ">
        <Separator className="text-primary bg-primary" />
        <p>*Report generated by system on {new Date().toLocaleString()}</p>
        <p>
          Hope Horizon - Charity & Fundraising .&copy; 2025 All Rights Reserved{" "}
        </p>
        <p>Registered under the Trust Act of India</p>
        <div className="flex items-center gap-x-2">
          <h5>Contact Us</h5>
          <h5 className="flex items-center gap-x-2">
            <Mail size={15} /> donate@hopehorizon.org
          </h5>
        </div>
      </div>
    </div>
  );
}
